# 开发环境：默认配置
ruoyi:
  profile: /Users/official/ProjectEnv/project-official-doc/environment
server:
  port: 54321
spring:
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 1024MB
      # 设置总上传的文件大小
      max-request-size: 10240MB
logging:
  charset:
    file: UTF-8
    console: UTF-8